version: '3.8'

services:
  ds_hat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    command: php -S ds_hat:8006 public/index.php
    restart: always